In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

In [2]:
# Directory where the CSV files are located
directory = "clean_csv/P06"

# Pattern to match CSV files
file_pattern = "*.csv"

# Get the file names matching the pattern for P03
file_names_p01 = glob.glob(directory + "/" + file_pattern)

In [11]:
for index, file_name in enumerate(file_names_p01):
    # Read the CSV file
    df = pd.read_csv(file_name)
    df = df.drop(columns="Unnamed: 0")

    #keep only document name
    file_name=file_name.split("\\")[1]
    print(file_name)

    if index == 0:
        main_df = df
        continue

    main_df = pd.merge(main_df,df,how="outer",on="TraceabilityCode",suffixes=("",f"_{index}"))
    if index == 10:
        break

P06-ClutchBrakeTemperatureUnitOil-values.csv
P06-ClutchBrakeWaterTemperature-values.csv
P06-DieReference.csv
P06-Gear1MaxTorque-values.csv
P06-Gear2MaxTorque-values.csv
P06-Gear3MaxTorque-values.csv
P06-HELMGaugesControl-values.csv
P06-LubricationTemperatureUnitOil-values.csv
P06-MainMotorMaxPower-values.csv
P06-MainMotorMeanPower-values.csv
P06-MaxForceFL-values.csv

In [12]:
main_df

,time,TraceabilityCode,ClutchBrakeTemperatureUnitOil,time.value,time_1,ClutchBrakeWaterTemperature,time.value_1,time_2,DieReference,time.reference,...,time.value_7,time_8,MainMotorMaxPower,time.value_8,time_9,MainMotorMeanPower,time.value_9,time_10,MaxForceFL,time.value_10
0,2023-01-04 14:48:47.447,1010223004134159,44.0,2023-01-04 14:48:53.135,NaN,NaN,NaN,2023-01-04 14:48:47.447,28,2023-01-04 14:10:52.352,...,2023-01-04 14:48:53.135,2023-01-04 14:48:47.447,201.0,2023-01-04 14:48:53.135,2023-01-04 14:48:47.447,87.6,2023-01-04 14:48:53.135,2023-01-04 14:48:47.447,1.9,2023-01-04 14:48:53.135
1,2023-01-04 14:48:59.546,1010123004134206,44.1,2023-01-04 14:49:03.956,NaN,NaN,NaN,2023-01-04 14:48:59.546,28,2023-01-04 14:10:52.352,...,2023-01-04 14:49:03.956,2023-01-04 14:48:59.546,185.1,2023-01-04 14:49:03.956,2023-01-04 14:48:59.546,78.7,2023-01-04 14:49:03.956,2023-01-04 14:48:59.546,1.4,2023-01-04 14:49:03.956
2,2023-01-04 14:51:04.079,1010123004134213,44.3,2023-01-04 14:51:08.339,NaN,NaN,NaN,2023-01-04 14:51:04.079,28,2023-01-04 14:10:52.352,...,NaN,2023-01-04 14:51:04.079,195.0,2023-01-04 14:51:08.339,2023-01-04 14:51:04.079,83.5,2023-01-04 14:51:08.339,2023-01-04 14:51:04.079,2.0,2023-01-04 14:51:08.339
3,2023-01-04 14:51:11.589,1010123004134220,44.4,2023-01-04 14:51:15.940,NaN,NaN,NaN,2023-01-04 14:51:11.589,28,2023-01-04 14:10:52.352,...,2023-01-04 14:51:15.940,2023-01-04 14:51:11.589,182.7,2023-01-04 14:51:15.940,2023-01-04 14:51:11.589,77.2,2023-01-04 14:51:15.940,2023-01-04 14:51:11.589,1.0,2023-01-04 14:51:15.940
4,2023-01-04 14:51:19.000,1010123004134227,44.6,2023-01-04 14:51:23.369,NaN,NaN,NaN,2023-01-04 14:51:19.000,28,2023-01-04 14:10:52.352,...,2023-01-04 14:51:23.369,2023-01-04 14:51:19.000,180.0,2023-01-04 14:51:23.369,2023-01-04 14:51:19.000,74.9,2023-01-04 14:51:23.369,2023-01-04 14:51:19.000,1.8,2023-01-04 14:51:23.369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163348,NaN,1010223059225654,NaN,NaN,NaN,NaN,NaN,2023-02-28 23:58:17.331,47,2023-02-28 19:08:25.229,...,2023-02-28 23:58:21.980,2023-02-28 23:58:17.331,144.6,2023-02-28 23:58:21.980,2023-02-28 23:58:17.331,57.8,2023-02-28 23:58:21.980,2023-02-28 23:58:17.331,1.2,2023-02-28 23:58:21.980
163349,NaN,1010223059225720,NaN,NaN,NaN,NaN,NaN,2023-02-28 23:58:42.671,47,2023-02-28 19:08:25.229,...,2023-02-28 23:58:47.421,2023-02-28 23:58:42.671,147.3,2023-02-28 23:58:47.421,2023-02-28 23:58:42.671,58.4,2023-02-28 23:58:47.421,2023-02-28 23:58:42.671,1.5,2023-02-28 23:58:47.421
163350,NaN,1010223059225728,NaN,NaN,NaN,NaN,NaN,2023-02-28 23:58:51.071,47,2023-02-28 19:08:25.229,...,2023-02-28 23:58:55.819,2023-02-28 23:58:51.071,147.0,2023-02-28 23:58:55.819,2023-02-28 23:58:51.071,58.0,2023-02-28 23:58:55.819,2023-02-28 23:58:51.071,1.2,2023-02-28 23:58:55.819
163351,NaN,1010223059225753,NaN,NaN,NaN,NaN,NaN,2023-02-28 23:59:16.220,47,2023-02-28 19:08:25.229,...,2023-02-28 23:59:20.940,2023-02-28 23:59:16.220,143.4,2023-02-28 23:59:20.940,2023-02-28 23:59:16.220,57.4,2023-02-28 23:59:20.940,2023-02-28 23:59:16.220,1.4,2023-02-28 23:59:20.940
163352,NaN,1010223059225835,NaN,NaN,NaN,NaN,NaN,2023-02-28 23:59:58.338,47,2023-02-28 19:08:25.229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN